[mypy]
files = src/, tests/
disallow_untyped_defs = true
disallow_untyped_calls = true 
explicit_package_bases = true

[mypy-pandas.*]
ignore_missing_imports = true

[mypy-yaml.*]
ignore_missing_imports = true

[mypy-ortools.*]
ignore_missing_imports = true

[mypy-anytree.*]
ignore_missing_imports = true

[mypy-gems.*]
ignore_missing_imports = true
ignore_errors = true

[mypy-antlr4.*]
ignore_missing_imports = true